export const formatNumber = (value: number) => value.toLocaleString('en-US');

export * from './auth';
export * from './said';
export * from './institutions';
export * from './conferences';
export * from './journals';
export * from './research';
export * from './lifecycle';
export * from './researchers';
export * from './intelligence';
export * from './ads';
export * from './marketplace';
export { discountPercentOf, invoiceTotal } from './commerce';
export * from './commerce';
export * from './services';
export { toDiscoveryItem, toDiscoveryItems } from './marketplace';
export * from './trust';
export {
  archiveNotification,
  buildEmailDigest,
  buildNotificationUrl,
  buildPushPayload,
  countByStatus,
  createNotification,
  digestCutoff,
  digestNotifications,
  dismissNotification,
  filterNotifications,
  groupByCategory,
  groupByPriority,
  markRead,
  markUnread,
  notificationAnalytics,
  notificationId,
  notificationStatistics,
  notificationsByChannel,
  notificationsByLifecycle,
  notificationsBySource,
  notificationsBySourceType,
  notificationsForUser,
  publishNotification,
  searchNotifications,
  shouldDeliver,
  sortNotifications,
  targetsNotification,
} from './notifications';
export type { NotificationFilter, NotificationSort } from './notifications';
export * from './messages';
export {
  ACTIVITY_SOURCES,
  ACTIVITY_TYPES,
  activityAnalytics,
  activityId,
  activityInsights,
  activityStatistics,
  activityUrl,
  addComment,
  addReaction,
  addReply,
  applyModeration,
  bookmarkCount,
  bookmarksForActivity,
  buildActivityUrl,
  buildFeeds,
  canViewActivity,
  commentCount,
  commentsForActivity,
  createActivity,
  discoveryFeed,
  disciplineFeed,
  engagementScore,
  extractHashtags,
  extractMentions,
  featuredActivities,
  feedForKind,
  filterActivities,
  followingFeed,
  fundingFeed,
  groupActivitiesByDay,
  hashtagsForActivities,
  institutionFeed,
  journalFeed,
  conferenceFeed,
  moderationQueue,
  moderationStatusOf,
  pinActivity,
  pinnedActivitiesForUser,
  recommendationScore,
  recommendedActivities,
  removeReaction,
  replyCount,
  reportActivity,
  resolveEngagement,
  resolveReport,
  resolveVisibility,
  searchActivities,
  shareCount,
  sharesForActivity,
  shouldModerate,
  sortActivities,
  toggleBookmark,
  trendScore,
  trendingActivities,
  unpinActivity,
  visibleActivities,
  activitiesByFeedKind,
  activitiesByType,
  activitiesByVisibility,
} from './activity';
export type { ActivityFeedOptions, ActivityViewer } from './activity';
export {
  activeMembers,
  addMember,
  achievedMilestones,
  buildCollaborationPortfolio,
  buildWorkspaceSlug,
  canEditWorkspace,
  canManageWorkspace,
  canViewWorkspace,
  changeMemberRole,
  collaborationAnalytics,
  collaborationInsights,
  collaborationStatistics,
  COLLABORATION_DOCUMENT_TYPES,
  COLLABORATION_INVITATION_STATUSES,
  COLLABORATION_LOG_EVENT_TYPES,
  COLLABORATION_MEMBER_ROLES,
  COLLABORATION_MEMBER_STATUSES,
  COLLABORATION_MILESTONE_STATUSES,
  COLLABORATION_TASK_PRIORITIES,
  COLLABORATION_TASK_STATUSES,
  COLLABORATION_WORKSPACE_KINDS,
  COLLABORATION_WORKSPACE_STATUSES,
  COLLABORATION_WORKSPACE_VISIBILITIES,
  completedTasks,
  createTask,
  createWorkspace,
  discussionId,
  discussionsByStatus,
  discussionsOf,
  documentId,
  documentsByType,
  documentsOf,
  eventsByType,
  eventsForWorkspace,
  filterWorkspaces,
  invitationId,
  invitationsByStatus,
  invitationsOf,
  logEntryId,
  meetingId,
  meetingsByStatus,
  meetingsOf,
  memberCount,
  memberOf,
  memberRoleOf,
  membersOf,
  milestoneId,
  milestonesByStage,
  milestonesByStatus,
  milestonesOf,
  openDiscussions,
  openTasks,
  overdueTasks,
  pendingInvitations,
  publishedDocuments,
  removeMember,
  repliesForDiscussion,
  resolvedDiscussions,
  searchWorkspaces,
  sortWorkspaces,
  taskId,
  tasksByPriority,
  tasksByStatus,
  tasksForAssignee,
  tasksOf,
  updateTaskStatus,
  upcomingMeetings,
  workspaceId,
  workspaceUrl,
  workspacesByKind,
  workspacesByVisibility,
  workspacesForUser,
} from './collaboration';
export type {
  CollaborationAnalytics,
  CollaborationFilter,
  CollaborationInsight,
  CollaborationMember,
  CollaborationPortfolio,
  CollaborationSort,
  CollaborationStatistics,
  CollaborationWorkspace,
  WorkspaceDiscussion,
  WorkspaceDocument,
  WorkspaceInvitation,
  WorkspaceLogEntry,
  WorkspaceMeeting,
  WorkspaceMilestone,
  WorkspaceTask,
} from '@/types/collaboration';
